### PR TITLE
Change golang requirement

### PR DESCRIPTION
**Pull request by andywaltlova**
test build

### CODE REVIEW

**Comment by SpyTec** [comment]
@andywaltlova want me to test downstream to see if it works there?

**Comment by andywaltlova** [comment]
Sure, if you can, my idea was to try it because I didn't found 1.20 version in developer tools (used https://access.redhat.com/downloads/content/package-browser to find the name) , wanted to adjust the spec file to use different names for fedora and rhel :)

**Comment by SpyTec** [comment]
@andywaltlova No luck :<

```
ERROR: Command failed: 
 # /usr/bin/yum-builddep --installroot /mnt/build/mock/rhel-7.9-z-build-10321362-7304824/root/ /mnt/build/mock/rhel-7.9-z-build-10321362-7304824/root//builddir/build/SRPMS/rhc-worker-bash-0.2-1.el7_9.src.rpm --setopt=tsflags=nocontexts
Getting requirements for rhc-worker-bash-0.2-1.el7_9.src
Error: No Package found for go-toolset-1.19-golang
```

**Comment by andywaltlova** [comment]
@SpyTec if yo utry it now? with `go-toolset-1.16-golang` (same as rhc has)

**Comment by SpyTec** [comment]
@andywaltlova same thing :<

```
 # /usr/bin/yum-builddep --installroot /mnt/build/mock/rhel-7.9-z-build-10321604-7304824/root/ /mnt/build/mock/rhel-7.9-z-build-10321604-7304824/root//builddir/build/SRPMS/rhc-worker-bash-0.2-1.el7_9.src.rpm --setopt=tsflags=nocontexts
Getting requirements for rhc-worker-bash-0.2-1.el7_9.src
Error: No Package found for go-toolset-1.16-golang
```

**Pull request closed without merging**
